import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for Instant SWMS.",
};

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="legal-updated">Last updated: 27 July 2026</p>

      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of the Instant SWMS website and
        document generation service (the &quot;Service&quot;). By using the Service, you agree to
        these Terms. If you don&apos;t agree, don&apos;t use the Service.
      </p>

      <h2>1. What the Service does</h2>
      <p>
        Instant SWMS generates draft Safe Work Method Statement (SWMS) documents based on the
        information you provide about your business and the job. Documents are produced by our
        automated system and delivered as downloadable PDF files.
      </p>

      <h2>2. Your responsibility — this is not professional advice</h2>
      <p>
        The Service produces <strong>draft documents only</strong>. It does not provide legal,
        safety, or professional advice, and it is not a substitute for a qualified work health
        and safety professional.
      </p>
      <ul>
        <li>
          Every SWMS generated by the Service <strong>must be reviewed, amended where necessary,
          and approved by a competent person</strong> before it is used on any work site.
        </li>
        <li>
          You are solely responsible for ensuring your SWMS accurately reflects the actual work,
          site conditions, plant, and personnel, and that it complies with the WHS/OHS laws that
          apply to you.
        </li>
        <li>
          You are responsible for consulting with workers, implementing the controls described,
          and keeping the document current as conditions change, as required by law.
        </li>
      </ul>
      <p>
        The accuracy and completeness of a generated document depends on the accuracy and
        completeness of the information you provide.
      </p>

      <h2>3. Accounts and access</h2>
      <p>
        The Service doesn&apos;t require an account. Access to purchased documents is provided
        through download links and document codes. Keep these private — anyone with the link can
        access the document.
      </p>

      <h2>4. Payment</h2>
      <p>
        Prices are listed on the site in Australian dollars. Payment is processed by Stripe; we
        never see or store your card details. Multi-document packs are redeemed via generation
        tokens which expire as described at purchase. Refunds are handled under our{" "}
        <a href="/refunds">Refund Policy</a>.
      </p>

      <h2>5. Intellectual property</h2>
      <p>
        You own the SWMS documents you generate and pay for, and you may use them freely in your
        business. We retain all rights in the Service itself, including its software, designs,
        templates, and branding.
      </p>

      <h2>6. Acceptable use</h2>
      <ul>
        <li>Don&apos;t use the Service for anything unlawful.</li>
        <li>Don&apos;t attempt to interfere with, reverse engineer, or disrupt the Service.</li>
        <li>Don&apos;t resell generated documents as your own template product.</li>
      </ul>

      <h2>7. Liability</h2>
      <p>
        Nothing in these Terms excludes, restricts, or modifies any consumer guarantee, right, or
        remedy under the Australian Consumer Law that cannot lawfully be excluded.
      </p>
      <p>
        Subject to that: the Service is provided &quot;as is&quot;; we do not warrant that any
        generated document is complete, accurate, or compliant with the laws that apply to your
        specific circumstances; and to the maximum extent permitted by law, our total liability
        for any claim arising out of the Service is limited to the amount you paid for the
        relevant document, and we are not liable for indirect or consequential loss, including
        loss arising from the use of a generated document on a work site.
      </p>

      <h2>8. Changes</h2>
      <p>
        We may update the Service and these Terms from time to time. The version published on
        this page applies from its &quot;last updated&quot; date. Continued use of the Service
        after changes means you accept the updated Terms.
      </p>

      <h2>9. Governing law</h2>
      <p>
        These Terms are governed by the laws of New South Wales, Australia, and you submit to the
        non-exclusive jurisdiction of its courts.
      </p>

      <h2>10. Contact</h2>
      <p>
        Questions? Email{" "}
        <a href="mailto:support@swmsgenerator.com.au">support@swmsgenerator.com.au</a>.
      </p>
    </>
  );
}
